language: node_js
node_js:
  - "4.0"

install:
  - npm install -g mocha
  - npm install

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install mongodb-org=3.0.5 mongodb-org-server=3.0.5 mongodb-org-shell=3.0.5 mongodb-org-mongos=3.0.5 mongodb-org-tools=3.0.5
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

after_script:
  - mongo --version

services:
  - mongodb
