language: node_js
node_js:
  - "4.0"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm install -g mocha
  - npm install

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

after_script:
  - mongo --version

services:
  - mongodb
